baseurl = "https://skaterdude97.github.io"
languageCode = "en-us"
title = "Andrei Stoica - Code Corner"
theme = "light-hugo"

author = "Andrei Stoica"
copyright = "© Copyright 2019 Andrei Stoica"

[Params]
	email = "andrei.stoica.365@gmail.com"
	github = "skaterdude97"
	linkedin = "andrei-stoica"
