languageCode = "en-us"
title = "Code Corner"
theme = "light-hugo"

author = "Andrei Stoica"
copyright = "© Copyright 2017 Andrei Stoica"

[Params]
	email = "andrei.stoica.365@gmail.com"
	github = "skaterdude97"
	linkedin = "andrei-stoica"

